# Generated by Django 4.2.8 on 2024-05-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=10, verbose_name='enter password')),
            ],
        ),
    ]
